# Generated by Django 2.0.3 on 2018-03-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='buildingName',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='room',
            name='storey',
            field=models.IntegerField(null=True),
        ),
    ]
