# Generated by Django 2.0.3 on 2018-03-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180310_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
