# Generated by Django 2.0.3 on 2018-03-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180310_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='duration',
        ),
        migrations.AddField(
            model_name='room',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
