# Generated by Django 2.0.3 on 2018-03-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180310_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='caption',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
